/* generated by dia/codegen.py */
/*(NULL)*/
class Facade 
{
public:
	Facade ();
	~Facade ();
	void OperationWrapper ();
private:
	SubSystem1*  _subsys1;
	SubSystem2* _subsys2;
};

class SubSystem1 
{
public:
	SubSystem1 ();
	~SubSystem1 ();
	void Operation ();
};

class Client 
{
};

class SubSystem2 
{
public:
	SubSystem2 ();
	~SubSystem2 ();
	void Operation ();
};

