/* generated by dia/codegen.py */
/*(NULL)*/
class ConcreteComponent : Component 
{
public:
	ConcreteComponent ();
	~ConcreteComponent ();
	void Operation ();
};

/*(NULL)*/
class Component 
{
public:
	Component ();
	~Component ();
	void Operation ();
};

/*(NULL)*/
class ConcreteDecoratorD : Decorator 
{
public:
	ConcreteDecoratorD ();
	~ConcreteDecoratorD ();
	void Operation ();
private:
	void AddBehavorD ();
};

/*(NULL)*/
class ConcreteDecoratorB : Decorator 
{
public:
	ConcreteDecoratorB ();
	~ConcreteDecoratorB ();
	void Operation ();
private:
	void AddBehavorB ();
};

/*(NULL)*/
class ConcreteDecoratorC : Decorator 
{
public:
	ConcreteDecoratorC ();
	~ConcreteDecoratorC ();
	void Operation ();
private:
	void AddBehavorC ();
};

/*(NULL)*/
class Decorator : Component 
{
public:
	Decorator ();
	~Decorator ();
	void Operation ();
};

/*(NULL)*/
class ConcreteDecoratorA : Decorator 
{
public:
	ConcreteDecoratorA ();
	~ConcreteDecoratorA ();
	void Operation ();
private:
	void AddBehavorA ();
};

